# Generated by Django 5.1.2 on 2024-11-21 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clinicas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Administrador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("telefone", models.CharField(max_length=15)),
                ("data_contratacao", models.DateField()),
                ("salario", models.DecimalField(decimal_places=2, max_digits=10)),
                ("numero_residencial", models.CharField(max_length=10)),
                (
                    "clinica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinicas.clinica",
                    ),
                ),
                (
                    "endereco",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clinicas.endereco",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dentista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("cro", models.CharField(max_length=20, unique=True)),
                ("especialidade", models.CharField(max_length=100)),
                ("telefone", models.CharField(max_length=15)),
                ("salario", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_contratacao", models.DateField()),
                ("numero_residencial", models.CharField(max_length=10)),
                (
                    "clinica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinicas.clinica",
                    ),
                ),
                (
                    "endereco",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clinicas.endereco",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Secretario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("telefone", models.CharField(max_length=15)),
                ("data_contratacao", models.DateField()),
                ("salario", models.DecimalField(decimal_places=2, max_digits=10)),
                ("numero_residencial", models.CharField(max_length=10)),
                (
                    "clinica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinicas.clinica",
                    ),
                ),
                (
                    "endereco",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clinicas.endereco",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
