# Generated by Django 5.1.2 on 2024-11-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("funcionarios", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="administrador",
            name="endereco",
        ),
        migrations.RemoveField(
            model_name="dentista",
            name="endereco",
        ),
        migrations.RemoveField(
            model_name="secretario",
            name="endereco",
        ),
        migrations.AddField(
            model_name="administrador",
            name="bairro",
            field=models.CharField(default="bairro bairro", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="administrador",
            name="cep",
            field=models.CharField(default="cepcep", max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="administrador",
            name="cidade",
            field=models.CharField(default="aaaaaaaaa", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="administrador",
            name="rua",
            field=models.CharField(default="aaaaaaaaaaa", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="administrador",
            name="ultima_atualizacao",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="dentista",
            name="bairro",
            field=models.CharField(default="aaaaaaaaaaaaaaa", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dentista",
            name="cep",
            field=models.CharField(default="aaaaaaaaaaaaaaa", max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dentista",
            name="cidade",
            field=models.CharField(default="aaaaaaaaaaaaaa", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dentista",
            name="rua",
            field=models.CharField(default="aaaaaaaaaaaaa", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dentista",
            name="ultima_atualizacao",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="secretario",
            name="bairro",
            field=models.CharField(default="aaaaaaaaaaaaaaaa", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="secretario",
            name="cep",
            field=models.CharField(default="aaaaaaaaaaaaaaa", max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="secretario",
            name="cidade",
            field=models.CharField(default="aaaaaaaaaaaaaaa", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="secretario",
            name="rua",
            field=models.CharField(default="aaaaaaaaaaaaaaaaaaaaa", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="secretario",
            name="ultima_atualizacao",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
