# Generated by Django 5.1.2 on 2024-11-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "pacientes",
            "0002_alter_cliente_data_nascimento_alter_cliente_endereco_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="cpf",
            field=models.CharField(max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="data_nascimento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="historico_clinico",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="numero_residencial",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
