# Generated by Django 5.1.2 on 2024-11-22 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinicas", "0001_initial"),
        ("pacientes", "0003_alter_cliente_cpf_alter_cliente_data_nascimento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="nome",
            field=models.CharField(default="ppadrao", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cliente",
            name="data_nascimento",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="endereco",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clinicas.endereco",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="historico_clinico",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="numero_residencial",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefone",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
