# Generated by Django 5.1.2 on 2024-11-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacientes", "0004_cliente_nome_alter_cliente_data_nascimento_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="endereco",
        ),
        migrations.AddField(
            model_name="cliente",
            name="bairro",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="cep",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="cidade",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="rua",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="ultima_atualizacao",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
