# Generated by Django 5.1.2 on 2024-11-21 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("funcionarios", "0001_initial"),
        ("pacientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                ("custo", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("status", models.CharField(max_length=20)),
                ("link_resultado", models.URLField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pacientes.cliente",
                    ),
                ),
                (
                    "dentista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="funcionarios.dentista",
                    ),
                ),
                ("exames", models.ManyToManyField(to="exames.exame")),
            ],
        ),
    ]
