# Generated by Django 5.1.2 on 2024-11-21 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rua", models.CharField(max_length=100)),
                ("bairro", models.CharField(max_length=100)),
                ("cep", models.CharField(max_length=15)),
                ("cidade", models.CharField(max_length=100)),
                ("ultima_atualizacao", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Clinica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("numero", models.CharField(max_length=10)),
                (
                    "endereco",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinicas.endereco",
                    ),
                ),
            ],
        ),
    ]
