# Generated by Django 5.1.2 on 2024-11-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinicas", "0002_endereco_estado"),
        ("funcionarios", "0002_remove_administrador_endereco_and_more"),
        (
            "pacientes",
            "0005_remove_cliente_endereco_cliente_bairro_cliente_cep_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clinica",
            name="endereco",
        ),
        migrations.AddField(
            model_name="clinica",
            name="bairro",
            field=models.CharField(default="papapapa", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clinica",
            name="cep",
            field=models.CharField(default="cepcep", max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clinica",
            name="cidade",
            field=models.CharField(default="cidadecidade", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clinica",
            name="rua",
            field=models.CharField(default="rua rua", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clinica",
            name="ultima_atualizacao",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.DeleteModel(
            name="Endereco",
        ),
    ]
